### PR TITLE
Update warning so it actually says something

### PR DESCRIPTION
**Pull request by wgyt**

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Wait what this wasn't warning?! 😆

**Comment by wgyt** [comment]
@all-contributors add @wgyt for code and docs
(I added the warning and reported a mistake in the docs on discord)

**Comment by Sly-Little-Fox** [comment]
~~why am I not added to contributors list if I reported it on Discord~~

**Comment by Explosion-Scratch** [comment]
> ~why am I not added to contributors list if I reported it on Discord lol~

=| @all-contributors add @Sly-Little-Fox for bugs and ideas

**Comment by Sly-Little-Fox** [comment]
> > ~why am I not added to contributors list if I reported it on Discord lol~
> 
> =| @all-contributors add @Sly-Little-Fox for bugs and ideas

😃

**Pull request merged**
